module.exports = {
  WX_SESSION_GUID_ID:'bfe36bd6-d24e-1d17-7479-db552570e973',

  ERR_WX_LOGIN_FAILED: 'ERR_WX_LOGIN_FAILED',
  ERR_WX_GET_USER_INFO: 'ERR_WX_GET_USER_INFO',

  ERR_LOGIN_FAILED: 'ERR_LOGIN_FAILED',
  ERR_LOGIN_SESSION_NOT_RECEIVED: 'ERR_LOGIN_MISSING_SESSION',

  ERR_INVALID_PARAMS: 'ERR_INVALID_PARAMS',

}